/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as RepositoriesNewRouteImport } from './routes/repositories.new'
import { Route as RepositoriesRepoIdRouteImport } from './routes/repositories.$repoId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as RepositoriesRepoIdSettingsRouteImport } from './routes/repositories.$repoId.settings'
import { Route as RepositoriesRepoIdVideosVideoIdRouteImport } from './routes/repositories.$repoId.videos.$videoId'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRoute,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => VideosRoute,
} as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesRepoIdRoute = RepositoriesRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => RepositoriesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const RepositoriesRepoIdSettingsRoute =
  RepositoriesRepoIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => RepositoriesRepoIdRoute,
  } as any)
const RepositoriesRepoIdVideosVideoIdRoute =
  RepositoriesRepoIdVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => RepositoriesRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/repositories/$repoId/settings': typeof RepositoriesRepoIdSettingsRoute
  '/repositories/$repoId/videos/$videoId': typeof RepositoriesRepoIdVideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/repositories/$repoId/settings': typeof RepositoriesRepoIdSettingsRoute
  '/repositories/$repoId/videos/$videoId': typeof RepositoriesRepoIdVideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRouteWithChildren
  '/repositories/new': typeof RepositoriesNewRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/repositories/$repoId/settings': typeof RepositoriesRepoIdSettingsRoute
  '/repositories/$repoId/videos/$videoId': typeof RepositoriesRepoIdVideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/live'
    | '/login'
    | '/profile'
    | '/repositories'
    | '/videos'
    | '/admin/settings'
    | '/admin/users'
    | '/repositories/$repoId'
    | '/repositories/new'
    | '/videos/$videoId'
    | '/repositories/'
    | '/videos/'
    | '/repositories/$repoId/settings'
    | '/repositories/$repoId/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/live'
    | '/login'
    | '/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/repositories/$repoId'
    | '/repositories/new'
    | '/videos/$videoId'
    | '/repositories'
    | '/videos'
    | '/repositories/$repoId/settings'
    | '/repositories/$repoId/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/live'
    | '/login'
    | '/profile'
    | '/repositories'
    | '/videos'
    | '/admin/settings'
    | '/admin/users'
    | '/repositories/$repoId'
    | '/repositories/new'
    | '/videos/$videoId'
    | '/repositories/'
    | '/videos/'
    | '/repositories/$repoId/settings'
    | '/repositories/$repoId/videos/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/repositories/$repoId/settings': {
      id: '/repositories/$repoId/settings'
      path: '/settings'
      fullPath: '/repositories/$repoId/settings'
      preLoaderRoute: typeof RepositoriesRepoIdSettingsRouteImport
      parentRoute: typeof RepositoriesRepoIdRoute
    }
    '/repositories/$repoId/videos/$videoId': {
      id: '/repositories/$repoId/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/repositories/$repoId/videos/$videoId'
      preLoaderRoute: typeof RepositoriesRepoIdVideosVideoIdRouteImport
      parentRoute: typeof RepositoriesRepoIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RepositoriesRepoIdRouteChildren {
  RepositoriesRepoIdSettingsRoute: typeof RepositoriesRepoIdSettingsRoute
  RepositoriesRepoIdVideosVideoIdRoute: typeof RepositoriesRepoIdVideosVideoIdRoute
}

const RepositoriesRepoIdRouteChildren: RepositoriesRepoIdRouteChildren = {
  RepositoriesRepoIdSettingsRoute: RepositoriesRepoIdSettingsRoute,
  RepositoriesRepoIdVideosVideoIdRoute: RepositoriesRepoIdVideosVideoIdRoute,
}

const RepositoriesRepoIdRouteWithChildren =
  RepositoriesRepoIdRoute._addFileChildren(RepositoriesRepoIdRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRouteWithChildren
  RepositoriesNewRoute: typeof RepositoriesNewRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesRepoIdRoute: RepositoriesRepoIdRouteWithChildren,
  RepositoriesNewRoute: RepositoriesNewRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface VideosRouteChildren {
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosVideoIdRoute: VideosVideoIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
